<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $clients = [
            [
                'title' => 'Mr',
                'first_name' => 'David',
                'middle_name' => 'James',
                'last_name' => 'Anderson',
                'preferred_name' => 'Dave',
                'date_of_birth' => '1985-03-15',
                'email' => 'david.anderson@gmail.com',
                'password' => Hash::make('client123'),
                'password_mail' => 1,
                'email_verified_at' => now(),
                'postal_address' => '123 Main Street, Colombo 01, Sri Lanka',
                'telephone_number' => '+94 11 2345678',
                'mobile_number' => '+94 77 1234567',
                'ni_number' => 'NI123456A',
                'personal_utr_number' => 'UTR1234567890',
                'terms_signed' => now()->subDays(30),
                'photo_id_verified' => 1,
                'address_verified' => 1,
                'marital_status' => 'Married',
                'nationality' => 'Sri Lankan',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 1,
                'client_does_their_own_sa' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ms',
                'first_name' => 'Priya',
                'last_name' => 'Fernando',
                'date_of_birth' => '1990-07-22',
                'email' => 'priya.fernando@gmail.com',
                'password' => Hash::make('client123'),
                'password_mail' => 1,
                'email_verified_at' => now(),
                'postal_address' => '456 Galle Road, Negombo, Sri Lanka',
                'telephone_number' => '+94 31 2234567',
                'mobile_number' => '+94 70 2345678',
                'ni_number' => 'NI234567B',
                'personal_utr_number' => 'UTR2345678901',
                'terms_signed' => now()->subDays(45),
                'photo_id_verified' => 1,
                'address_verified' => 1,
                'marital_status' => 'Single',
                'nationality' => 'Sri Lankan',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 1,
                'client_does_their_own_sa' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr',
                'first_name' => 'Rajesh',
                'middle_name' => 'Kumar',
                'last_name' => 'Patel',
                'date_of_birth' => '1978-11-30',
                'email' => 'rajesh.patel@yahoo.com',
                'password' => Hash::make('client123'),
                'password_mail' => 0,
                'email_verified_at' => now(),
                'postal_address' => '789 Temple Road, Kandy, Sri Lanka',
                'telephone_number' => '+94 81 2345678',
                'mobile_number' => '+94 71 3456789',
                'ni_number' => 'NI345678C',
                'personal_utr_number' => 'UTR3456789012',
                'terms_signed' => now()->subDays(60),
                'photo_id_verified' => 1,
                'address_verified' => 1,
                'marital_status' => 'Married',
                'nationality' => 'Indian',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 1,
                'client_does_their_own_sa' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mrs',
                'first_name' => 'Amanda',
                'last_name' => 'Silva',
                'date_of_birth' => '1982-05-18',
                'email' => 'amanda.silva@outlook.com',
                'password' => Hash::make('client123'),
                'password_mail' => 1,
                'email_verified_at' => now(),
                'postal_address' => '321 Beach Road, Galle, Sri Lanka',
                'telephone_number' => '+94 91 2234567',
                'mobile_number' => '+94 76 4567890',
                'ni_number' => 'NI456789D',
                'personal_utr_number' => 'UTR4567890123',
                'terms_signed' => now()->subDays(15),
                'photo_id_verified' => 1,
                'address_verified' => 0,
                'marital_status' => 'Married',
                'nationality' => 'Sri Lankan',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 0,
                'client_does_their_own_sa' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dr',
                'first_name' => 'Mohammed',
                'middle_name' => 'Ali',
                'last_name' => 'Hassan',
                'date_of_birth' => '1975-09-10',
                'email' => 'mohammed.hassan@gmail.com',
                'password' => Hash::make('client123'),
                'password_mail' => 0,
                'email_verified_at' => now(),
                'postal_address' => '654 Hospital Road, Jaffna, Sri Lanka',
                'telephone_number' => '+94 21 2345678',
                'mobile_number' => '+94 72 5678901',
                'ni_number' => 'NI567890E',
                'personal_utr_number' => 'UTR5678901234',
                'terms_signed' => now()->subDays(90),
                'photo_id_verified' => 1,
                'address_verified' => 1,
                'marital_status' => 'Married',
                'nationality' => 'Sri Lankan',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 1,
                'client_does_their_own_sa' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Miss',
                'first_name' => 'Natasha',
                'last_name' => 'Perera',
                'date_of_birth' => '1995-12-05',
                'email' => 'natasha.perera@gmail.com',
                'password' => Hash::make('client123'),
                'password_mail' => 1,
                'email_verified_at' => now(),
                'postal_address' => '987 Park Avenue, Matara, Sri Lanka',
                'telephone_number' => '+94 41 2234567',
                'mobile_number' => '+94 75 6789012',
                'ni_number' => 'NI678901F',
                'personal_utr_number' => 'UTR6789012345',
                'terms_signed' => now()->subDays(7),
                'photo_id_verified' => 0,
                'address_verified' => 0,
                'marital_status' => 'Single',
                'nationality' => 'Sri Lankan',
                'preferred_language' => 'English',
                'create_self_assessment_client' => 1,
                'client_does_their_own_sa' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}