<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            [
                'company_number' => 'PV12345678',
                'company_name' => 'Tech Solutions Lanka (Pvt) Ltd',
                'company_status' => 'Active',
                'company_type' => 'Private Limited Company',
                'incorporation_date' => '2020-01-15',
                'company_trading_as' => 'Tech Solutions',
                'registered_address' => '123 Technology Park, Colombo 03, Sri Lanka',
                'company_postal_address' => '123 Technology Park, Colombo 03, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'info@techsolutionslanka.lk',
                'company_email_domain' => 'techsolutionslanka.lk',
                'company_telephone' => '+94 11 2345678',
                'turnover' => 5000000.00,
                'date_of_trading' => '2020-02-01',
                'sic_code' => '62012',
                'nature_of_business' => 'Software Development and IT Consulting',
                'corporation_tax_office' => 'Colombo Tax Office',
                'company_utr' => 'CTR1234567890',
                'companies_house_authentication_code' => 'AUTH123456',
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => 'PV23456789',
                'company_name' => 'Lanka Export Trading (Pvt) Ltd',
                'company_status' => 'Active',
                'company_type' => 'Private Limited Company',
                'incorporation_date' => '2018-06-20',
                'company_trading_as' => 'Lanka Exports',
                'registered_address' => '456 Export Zone, Katunayake, Sri Lanka',
                'company_postal_address' => 'P.O. Box 789, Negombo, Sri Lanka',
                'invoice_address_type' => 'Postal Address',
                'company_email' => 'contact@lankaexports.lk',
                'company_email_domain' => 'lankaexports.lk',
                'company_telephone' => '+94 31 2234567',
                'turnover' => 12000000.00,
                'date_of_trading' => '2018-07-01',
                'sic_code' => '46900',
                'nature_of_business' => 'Import Export Trading',
                'corporation_tax_office' => 'Negombo Tax Office',
                'company_utr' => 'CTR2345678901',
                'companies_house_authentication_code' => 'AUTH234567',
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => null,
                'company_name' => 'Silva Construction Services',
                'company_status' => 'Active',
                'company_type' => 'Sole Trader',
                'incorporation_date' => null,
                'company_trading_as' => 'Silva Construction',
                'registered_address' => '789 Main Road, Galle, Sri Lanka',
                'company_postal_address' => '789 Main Road, Galle, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'info@silvaconstruction.lk',
                'company_email_domain' => 'silvaconstruction.lk',
                'company_telephone' => '+94 91 2345678',
                'turnover' => 3500000.00,
                'date_of_trading' => '2015-03-01',
                'sic_code' => '41201',
                'nature_of_business' => 'Construction Services',
                'corporation_tax_office' => 'Galle Tax Office',
                'company_utr' => 'STR3456789012',
                'companies_house_authentication_code' => null,
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => 'LLP34567890',
                'company_name' => 'Professional Legal Associates LLP',
                'company_status' => 'Active',
                'company_type' => 'LLP',
                'incorporation_date' => '2019-09-10',
                'company_trading_as' => 'PLA Legal',
                'registered_address' => '321 Justice Square, Colombo 01, Sri Lanka',
                'company_postal_address' => '321 Justice Square, Colombo 01, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'admin@plalegal.lk',
                'company_email_domain' => 'plalegal.lk',
                'company_telephone' => '+94 11 2456789',
                'turnover' => 8000000.00,
                'date_of_trading' => '2019-10-01',
                'sic_code' => '69101',
                'nature_of_business' => 'Legal Services',
                'corporation_tax_office' => 'Colombo Tax Office',
                'company_utr' => 'LLP4567890123',
                'companies_house_authentication_code' => 'AUTH345678',
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => 'PV45678901',
                'company_name' => 'Green Tea Estates (Pvt) Ltd',
                'company_status' => 'Active',
                'company_type' => 'Private Limited Company',
                'incorporation_date' => '2017-02-28',
                'company_trading_as' => 'Green Tea Ceylon',
                'registered_address' => '654 Tea Estate Road, Nuwara Eliya, Sri Lanka',
                'company_postal_address' => '654 Tea Estate Road, Nuwara Eliya, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'info@greenteaceylon.lk',
                'company_email_domain' => 'greenteaceylon.lk',
                'company_telephone' => '+94 52 2234567',
                'turnover' => 15000000.00,
                'date_of_trading' => '2017-04-01',
                'sic_code' => '01270',
                'nature_of_business' => 'Tea Cultivation and Export',
                'corporation_tax_office' => 'Nuwara Eliya Tax Office',
                'company_utr' => 'CTR5678901234',
                'companies_house_authentication_code' => 'AUTH456789',
                'engagement' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => null,
                'company_name' => 'Fernando & Associates',
                'company_status' => 'Active',
                'company_type' => 'Partnership',
                'incorporation_date' => null,
                'company_trading_as' => 'Fernando Associates',
                'registered_address' => '987 Business Plaza, Kandy, Sri Lanka',
                'company_postal_address' => '987 Business Plaza, Kandy, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'contact@fernandoassociates.lk',
                'company_email_domain' => 'fernandoassociates.lk',
                'company_telephone' => '+94 81 2345678',
                'turnover' => 6500000.00,
                'date_of_trading' => '2016-01-15',
                'sic_code' => '69201',
                'nature_of_business' => 'Accounting and Tax Advisory',
                'corporation_tax_office' => 'Kandy Tax Office',
                'company_utr' => 'PTR6789012345',
                'companies_house_authentication_code' => null,
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_number' => 'PV56789012',
                'company_name' => 'Ocean Fresh Seafood (Pvt) Ltd',
                'company_status' => 'Active',
                'company_type' => 'Private Limited Company',
                'incorporation_date' => '2021-05-10',
                'company_trading_as' => 'Ocean Fresh',
                'registered_address' => '147 Fishery Harbor, Negombo, Sri Lanka',
                'company_postal_address' => '147 Fishery Harbor, Negombo, Sri Lanka',
                'invoice_address_type' => 'Registered Address',
                'company_email' => 'sales@oceanfresh.lk',
                'company_email_domain' => 'oceanfresh.lk',
                'company_telephone' => '+94 31 2456789',
                'turnover' => 9500000.00,
                'date_of_trading' => '2021-06-01',
                'sic_code' => '10201',
                'nature_of_business' => 'Seafood Processing and Export',
                'corporation_tax_office' => 'Negombo Tax Office',
                'company_utr' => 'CTR7890123456',
                'companies_house_authentication_code' => 'AUTH567890',
                'engagement' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($companies as $company) {
            Company::create($company);
        }
    }
}